import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life.",
    price: 129.99,
    image: "/placeholder.svg",
    category: "Electronics",
    inStock: true,
  },
  {
    id: 2,
    name: "Smart Watch",
    description: "Feature-rich smartwatch with fitness tracking, heart rate monitor, and GPS.",
    price: 249.99,
    image: "/placeholder.svg",
    category: "Electronics",
    inStock: true,
  },
  {
    id: 3,
    name: "Laptop Backpack",
    description: "Durable and stylish backpack with dedicated laptop compartment and USB charging port.",
    price: 59.99,
    image: "/placeholder.svg",
    category: "Accessories",
    inStock: true,
  },
  {
    id: 4,
    name: "Coffee Maker",
    description: "Programmable coffee maker with thermal carafe and auto-brew feature.",
    price: 89.99,
    image: "/placeholder.svg",
    category: "Home & Kitchen",
    inStock: true,
  },
  {
    id: 5,
    name: "Yoga Mat",
    description: "Premium non-slip yoga mat with extra cushioning for comfort during workouts.",
    price: 34.99,
    image: "/placeholder.svg",
    category: "Sports & Fitness",
    inStock: true,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    description: "Portable waterproof Bluetooth speaker with 360-degree sound and 12-hour playtime.",
    price: 79.99,
    image: "/placeholder.svg",
    category: "Electronics",
    inStock: false,
  },
  {
    id: 7,
    name: "Running Shoes",
    description: "Lightweight running shoes with responsive cushioning and breathable mesh upper.",
    price: 119.99,
    image: "/placeholder.svg",
    category: "Sports & Fitness",
    inStock: true,
  },
  {
    id: 8,
    name: "Desk Lamp",
    description: "LED desk lamp with adjustable brightness, color temperature, and USB charging port.",
    price: 45.99,
    image: "/placeholder.svg",
    category: "Home & Kitchen",
    inStock: true,
  },
];
